In [12]:
# Importing Libraries
import pandas as pd
import numpy as np
from scipy.stats import kurtosis
from scipy.stats import skew

In [3]:
# Loading fuel data  
url='https://github.com/WalePhenomenon/climate_change/blob/master/fuel_ferc1.csv?raw=true'
fuel_data = pd.read_csv(url, error_bad_lines=False)

record_id  utility_id_ferc1   report_year  \
count                     29523      29523.000000  29523.000000   
unique                    29523               NaN           NaN   
top     f1_fuel_2005_12_148_1_2               NaN           NaN   
freq                          1               NaN           NaN   
mean                        NaN        118.601836   2005.806050   
std                         NaN         74.178353      7.025483   
min                         NaN          1.000000   1994.000000   
25%                         NaN         55.000000   2000.000000   
50%                         NaN        122.000000   2006.000000   
75%                         NaN        176.000000   2012.000000   
max                         NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6         9              NaN   
top           big stone                 gas       mcf              NaN   
freq                156               11486     11354              NaN   
mean                NaN                 NaN       NaN     2.622119e+06   
std                 NaN                 NaN       NaN     9.118004e+06   
min                 NaN                 NaN       NaN     1.000000e+00   
25%                 NaN                 NaN       NaN     1.381700e+04   
50%                 NaN                 NaN       NaN     2.533220e+05   
75%                 NaN                 NaN       NaN     1.424034e+06   
max                 NaN                 NaN       NaN     5.558942e+08   

        fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
count          29523.000000               29523.000000   
unique                  NaN                        NaN   
top                     NaN                        NaN   
freq                    NaN                        NaN   
mean               8.492111                 208.649031   
std               10.600220                2854.490090   
min                0.000001                -276.080000   
25%                1.024000                   5.207000   
50%                5.762694                  26.000000   
75%               17.006000                  47.113000   
max              341.260000              139358.000000   

        fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
count                   2.952300e+04         29523.000000  
unique                           NaN                  NaN  
top                              NaN                  NaN  
freq                             NaN                  NaN  
mean                    9.175704e+02            19.304354  
std                     6.877593e+04          2091.540939  
min                    -8.749370e+02           -41.501000  
25%                     3.778500e+00             1.940000  
50%                     1.737100e+01             4.127000  
75%                     4.213700e+01             7.745000  
max                     7.964521e+06        359278.000000

# Question 1

In [5]:
np.array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
from numpy import eye
eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Question 2

In [75]:
coal_1998 = fuel_data['fuel_cost_per_unit_burned'][(fuel_data['fuel_type_code_pudl'] == 'coal') & (fuel_data['report_year']==1998)]
coal_1994 = fuel_data['fuel_cost_per_unit_burned'][(fuel_data['fuel_type_code_pudl'] == 'coal') & (fuel_data['report_year']==1994)]

percentage_change = (sum(coal_1994)-sum(coal_1998))/100
print(percentage_change)

30.819749999999985


# Question 3

In [ ]:
# Could not answer this question but will search for the answer.

# Question 4

In [ ]:
'''
from question 6 the feature with missing values is the fuel_unit feature and it is a categorical type 
because its made up of categories of measurements.
The type of imputation I will use is Mode imputation which replaces missing values of 
a categorical variable by the mode of non-missing cases of that variable.
'''

# Question 5

In [85]:
years = range(1994,2019)
accum = 0
for year in years:
    get_data = fuel_data['fuel_cost_per_unit_delivered'][(fuel_data['report_year']==year)]
    average = sum(get_data)/len(get_data)
    if average > accum:
        accum = average
        new_year =year
        
print('Year-{}, Average-{}'.format(new_year,accum))

Year-1997, Average-11140.19723948813


# Question 6

In [87]:
features = ['record_id','utility_id_ferc1','report_year','plant_name_ferc1','fuel_type_code_pudl','fuel_unit','fuel_qty_burned','fuel_mmbtu_per_unit','fuel_cost_per_unit_burned','fuel_cost_per_unit_delivered','fuel_cost_per_mmbtu']
for feature in features:
    p = fuel_data[feature].isnull()
    total = len(fuel_data[p == True])
    percent = (total/len(fuel_data))*100
    if total> 0:
        print('Feature: {}, Total: {}, Percent: {:.3f}'.format(feature,total,percent))


Feature: fuel_unit, Total: 180, Percent: 0.610


# Question 7

In [81]:
# skew_fqb is the skewness for the feature fuel quantity burned
skew_fqb = skew(fuel_data['fuel_qty_burned'])
print(skew_fqb)

# kurt_fqb is the kurtosis for the feature fuel quantity burned
kurt_fqb = kurtosis(fuel_data['fuel_qty_burned'])
print(kurt_fqb)

15.850690077422112
651.2589365474387


# Question 8

In [88]:
fuel_data.describe(include='all')

record_id  utility_id_ferc1   report_year  \
count                     29523      29523.000000  29523.000000   
unique                    29523               NaN           NaN   
top     f1_fuel_2005_12_148_1_2               NaN           NaN   
freq                          1               NaN           NaN   
mean                        NaN        118.601836   2005.806050   
std                         NaN         74.178353      7.025483   
min                         NaN          1.000000   1994.000000   
25%                         NaN         55.000000   2000.000000   
50%                         NaN        122.000000   2006.000000   
75%                         NaN        176.000000   2012.000000   
max                         NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6         9              NaN   
top           big stone                 gas       mcf              NaN   
freq                156               11486     11354              NaN   
mean                NaN                 NaN       NaN     2.622119e+06   
std                 NaN                 NaN       NaN     9.118004e+06   
min                 NaN                 NaN       NaN     1.000000e+00   
25%                 NaN                 NaN       NaN     1.381700e+04   
50%                 NaN                 NaN       NaN     2.533220e+05   
75%                 NaN                 NaN       NaN     1.424034e+06   
max                 NaN                 NaN       NaN     5.558942e+08   

        fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
count          29523.000000               29523.000000   
unique                  NaN                        NaN   
top                     NaN                        NaN   
freq                    NaN                        NaN   
mean               8.492111                 208.649031   
std               10.600220                2854.490090   
min                0.000001                -276.080000   
25%                1.024000                   5.207000   
50%                5.762694                  26.000000   
75%               17.006000                  47.113000   
max              341.260000              139358.000000   

        fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
count                   2.952300e+04         29523.000000  
unique                           NaN                  NaN  
top                              NaN                  NaN  
freq                             NaN                  NaN  
mean                    9.175704e+02            19.304354  
std                     6.877593e+04          2091.540939  
min                    -8.749370e+02           -41.501000  
25%                     3.778500e+00             1.940000  
50%                     1.737100e+01             4.127000  
75%                     4.213700e+01             7.745000  
max                     7.964521e+06        359278.000000

# Question 9

In [92]:
fuel_types = ['coal','waste','oil','gas']
accum = 100000
new_fuel_type = ''
for fuel_type in fuel_types:
    get_data = fuel_data['fuel_cost_per_unit_burned'][(fuel_data['fuel_type_code_pudl']==fuel_type)]
    average = sum(get_data)/len(get_data)
    if average<accum:
        accum=average
        new_fuel_type = fuel_type
    
print('Fuel Type-{}, Average-{}'.format(new_fuel_type,accum))

Fuel Type-gas, Average-13.659396569737135


# Question 10

In [98]:
A = [1,2,3,4,5,6]
B = [13, 21, 34]
A.extend(B)
print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 34]
